server:
  http_listen_port: 9100
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: job
    static_configs:
    - labels:
        job: excedente_wsgi
        __path__: /app/logs/*
